---
- hosts: localhost
  vars:
    - ansible_python_interpreter: /usr/local/bin/python
      region: us-east-1
  tasks:
    - name: create an instance
      local_action:
        module: ec2
        key_name: ********
        instance_type: t2.micro
        wait: yes
        count: 1
        region: "{{ region }}"
        aws_access_key: ***********
        aws_secret_key: ***********
        assign_public_ip: yes
      register: ec2_output

    - name: Get instance id
      set_fact:
        ec2id: "{{ ec2_outputinstances | map(attribute='id') | list }}"  
    
    - name: create an ami
    - ec2_ami:
        region: us_east_1
        reasource: "{{ item }}"
        aws_access_key: ************
        aws_secret_key: ************
        state: present
      with_items: "{{ ec2id }}"
      