AWSTemplateFormatVersion: 2010-09-09
Description: Create my first EC2 instance using cloudformation
Parameters:
  imageid: 
    Default: ***********
    Description: my ami
    Type: String
  InstanceType:
    Default: t2.micro
    Description: type of my instance
    Type: String
  keypair:
    Default: *******
    Description: Keypair instance
    Type: String
Resources:
  EC2instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ********** 
      InstanceType: t2.micro
      KeyName: ***** 
      SecurityGroupIds: 
         - !Ref WebAppSecurityGroup  
  WebAppSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
    GroupName: dev
    GroupDescription: "Allow HTTP,HTTPS&SSH Inbound and Outbound Traffic"
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0       