---
- hosts: localhost
  vars:
    - ansible_python_interpreter: /usr/local/bin/python
  tasks:
    - name: create a cloudformation stack
      cloudformation:
        stack_name: "ansible-cloudformation stack"
        state: "present"
        region: "us-east-1"
        disable_rollback: true
        template: "files/cloudformation name.yaml"
        template_parameters:
          KeyName: "xxxxxxx"
          DiskType: "xxxxxxx"
          InstanceType: "t2.micro"
          ClusterSize: 3
        tags:
          Stack: "ansible-cloudformation"
        aws_access_key: xxxxxxx
        aws_secret_key: xxxxxxxxxx
    