---
- hosts: localhost
  vars:
   - ansible_python_interpreter: /usr/bin/python
  tasks:
    - ec2_ami:
        instance_id: i-xxxxxxx
        region: us-east-1
        wait: yes
        name: ec2-ami
        aws_access_key: xxxxxxxxxxxxxx
        aws_secret_key: xxxxxxxxxxxxxx
