---
- hosts: localhost
  vars:
   - ansible_python_interpreter: /usr/bin/python
  tasks:
   - name:  to create a cloudformation stack
     cloudformation:
       stack_name: "ansible-cloudformation"
       state: "present"
       region: "us-east-1"
       aws_access_key: xxxxxxxxxx
       aws_secret_key: xxxxxxxxxx
       disable_rollback: true
       template: "Desktop/ec2instance.yaml"
       template_parameters:
         KeyName: "xxxxxxxxxx"
         InstanceType: "t2.micro"
