---
- hosts: localhost
  vars:
    - ansible_python_interpreter: /usr/local/bin/python
  tasks:
    - name: create an ec2 instance
      local_action:
        module: ec2
        key_name: xxxxxxx
        instance_type: t2.micro
        image: ami-********
        wait: yes
        count: 1
        vpc_subnet_id: xxxxxxx
        region: us-east-1
        aws_access_key: xxxxxxx
        aws_secret_key: xxxxxxxxxx
        assign_public_ip: yes