---
- name: Terminate ec2 instance
  hosts: localhost
  vars:
   - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Terminate instance launched above
      ec2:
        region: us-east-1
        state: 'absent'
        instance_ids: i-xxxxxxxxx
        aws_access_key: xxxxxxxxxxxx
        aws_secret_key: xxxxxxxxxxx
