---
- hosts: localhost
  vars:
   - ansible_python_interpreter: /usr/bin/python
  tasks:
    - ec2_snapshot:
        instance_id: i-xxxxxxx
        region: us-east-1
        device_name: /dev/xvda
        wait: yes
        aws_access_key: xxxxxxxxxxxxxx
        aws_secret_key: xxxxxxx
