AWSTemplateFormatVersion: 2010-09-09
Description: create an autoscaling group
Parameters:
  EnvironmentName:
    Default: autoscalingenv
    Description: An environment name that is prefixed to resource names
    Type: String
  ImageId:
    Default: ami-0b5eea76982371e91
    Description: ami imageid
    Type: String
  InstanceType:
    Default: t2.micro
    Description: instance type
    Type: String
  KeyPair:
    Default: nov2022
    Description: key pair name
    Type: String
Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${EnvironmentName}-LaunchTemplate
      LaunchTemplateData:
         ImageId: !Ref ImageId
         InstanceType: !Ref InstanceType
         KeyName: !Ref KeyPair
  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: MyLaunchTemplate
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-AutoScaleGroup
      DesiredCapacity: '1'
      MinSize: '1'
      MaxSize: '5'
      LaunchTemplate:
        LaunchTemiplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
       - !Ref TargetGroup
      AvailabilityZones:
        - us-east-1a
        - us-east-1b
        - us-east-1c
      Tags:
        - Key: Environment
          Value: production
          PropagateAtLaunch: false
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-TargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: vpc-04939b8e346a8be9f
      TargetType: instance
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-LoadBalancer
      Type: application
      IpAddressType: ipv4
      Subnets:
        - subnet-0af24f47e4a29e378
        - subnet-0e19535bc1d3ed4a3
        - subnet-0c3cd014c83e7827b
      Tags:
       - Key: alb
         Value: !Ref EnvironmentName